-- 1.0005 changes --
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (101, 35, 'Exceptions', 'UPDATE+employees+SET+salary+%3D+salary+%2B+100+WHERE+emp_id+%3D+1%3B%0Aselect+*+from+DB2INST1.EMP+WHERE+1%3D1%3B%0ASELECT+*+FROM+NON_EXISTING_TABLE%3B%0Aselect+*+from+CREDITCARDS%3B%0ASelect+*+from+CCN%3B%0ASELECT+*+FROM+HR.SALARIES+WHERE+security_label+%3D+%27TOP_SECRET%27%3B%0ADROP+TABLE+CUSTOMERS%3B', 'Exceptions issues DB2', 'db2', 'Updates, Selects and DROP in DB2 fro Exceptions', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (102, 35, 'Exceptions', '--+Create+a+New+Schema%0ACREATE+SCHEMA+CLONE+AUTHORIZATION+db2inst1%3B%0A%0A--+Clone+the+CQWCOL.CUSTOMER+Table+into+the+New+Schema%0ACREATE+TABLE+CLONE.CUSTOMER+AS+%28SELECT+*+FROM+CQWCOL.CUSTOMER%29+WITH+NO+DATA%3B%0A%0A--+Insert+Data+in+Batches+of+100+Rows+%281st+Batch%29%0AINSERT+INTO+CLONE.CUSTOMER+%0ASELECT+*+FROM+CQWCOL.CUSTOMER%0AFETCH+FIRST+100+ROWS+ONLY%3B%0A%0A--+Insert+Data+in+Batches+of+100+Rows+%282nd+Batch%29%0AINSERT+INTO+CLONE.CUSTOMER%0ASELECT+*%0AFROM+CQWCOL.CUSTOMER%0AOFFSET+100+ROWS+FETCH+NEXT+100+ROWS+ONLY%3B%0A%0A--+Insert+Data+in+Batches+of+100+Rows+%283rd+Batch%29%0AINSERT+INTO+CLONE.CUSTOMER%0ASELECT+*%0AFROM+CQWCOL.CUSTOMER%0AOFFSET+200+ROWS+FETCH+NEXT+100+ROWS+ONLY%3B%0A%0A--+Insert+Data+in+Batches+of+100+Rows+%284th+Batch%29%0AINSERT+INTO+CLONE.CUSTOMER%0ASELECT+*%0AFROM+CQWCOL.CUSTOMER%0AOFFSET+300+ROWS+FETCH+NEXT+100+ROWS+ONLY%3B%0A%0A--+Select+Data+%0ASELECT+*+FROM+CLONE.CUSTOMER%3B%0ASELECT+*+FROM+CQWCOL.CUSTOMER%3B%0A%0A--+Grant+All+Privileges+to+User+on+the+Cloned+Table%0AGRANT+ALL+PRIVILEGES+ON+TABLE+CLONE.CUSTOMER+TO+USER+polly%3B%0AGRANT+ALL+PRIVILEGES+ON+TABLE+CLONE.CUSTOMER+TO+USER+liher%3B%0AGRANT+ALL+PRIVILEGES+ON+TABLE+CLONE.CUSTOMER+TO+USER+jason%3B%0AGRANT+ALL+PRIVILEGES+ON+TABLE+CLONE.CUSTOMER+TO+USER+john%3B%0AGRANT+ALL+PRIVILEGES+ON+TABLE+CLONE.CUSTOMER+TO+USER+ian%3B%0A%0A--+Grant+Data+Access+Privileges+to+User+%0AGRANT+SELECT%2C+INSERT%2C+UPDATE%2C+DELETE+ON+TABLE+CLONE.CUSTOMER+TO+USER+polly%3B%0AGRANT+SELECT%2C+INSERT%2C+UPDATE%2C+DELETE+ON+TABLE+CLONE.CUSTOMER+TO+USER+liher%3B%0AGRANT+SELECT%2C+INSERT%2C+UPDATE%2C+DELETE+ON+TABLE+CLONE.CUSTOMER+TO+USER+jason%3B%0AGRANT+SELECT%2C+INSERT%2C+UPDATE%2C+DELETE+ON+TABLE+CLONE.CUSTOMER+TO+USER+john%3B%0AGRANT+SELECT%2C+INSERT%2C+UPDATE%2C+DELETE+ON+TABLE+CLONE.CUSTOMER+TO+USER+ian%3B%0A%0A--+Drop+the+Cloned+Table%0ADROP+TABLE+CLONE.CUSTOMER%3B%0A%0A--+Drop+the+New+Schema%0ADROP+SCHEMA+CLONE+RESTRICT%3B', 'Clone Data in DB2', 'db2', 'Clone data in newly create schema DB2', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (109, 35, 'Drop', '--+Drop+the+Cloned+Table%0ADROP+TABLE+HR.EMPLOYEES%3B', 'Drop HR.Employees', 'db2', 'This will drop HR.Employees', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (110, 35, 'Drop', '--+Drop+the+HR+Schema%0ADROP+SCHEMA+HR+RESTRICT%3B%0A', 'Drop HR Schema', 'db2', 'This will drop HR Schema', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (103, 35, 'Exceptions', '--+Create+a+New+Schema%0ACREATE+SCHEMA+HR+AUTHORIZATION+db2inst1%3B%0A%0A--+Clone+the+Existing+Employees+Table+into+the+New+Schema%0ACREATE+TABLE+HR.EMPLOYEES+AS+%28SELECT+*+FROM+db2inst1.EMP%29+WITH+DATA%3B%0A%0A--+Alter+the+Cloned+Table%3A+Add+a+New+Column%0AALTER+TABLE+HR.EMPLOYEES+ADD+COLUMN+DEPARTMENT+VARCHAR%2850%29+DEFAULT+%27General%27%3B%0A%0ASELECT+*+FROM+HR.EMPLOYEES+WHERE+EMPNO+%3D+%27000010%27%3B%0A%0A--+Update+a+Record+in+the+Cloned+Table%0AUPDATE+HR.EMPLOYEES+SET+SALARY+%3D+190000++WHERE+EMPNO+%3D+%27000010%27%3B%0A%0ASELECT+*+FROM+HR.EMPLOYEES+WHERE+EMPNO+%3D+%27000010%27%3B%0A%0A--+Delete+a+Record+from+the+Cloned+Table%0ADELETE+FROM+HR.EMPLOYEES+WHERE+EMPNO+%3D+%27000010%27%3B%0A%0A--+Drop+the+Cloned+Table%0ADROP+TABLE+HR.EMPLOYEES%3B%0A%0A--+Drop+the+New+Schema%0ADROP+SCHEMA+HR+RESTRICT%3B%0A', 'Create and Drop schema with actions performed', 'db2', 'Create new schema in DB2 perform some actions then drop', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (104, 35, 'Update', '--+Create+a+New+Schema%0ACREATE+SCHEMA+HR+AUTHORIZATION+db2inst1%3B%0A', 'Create schema HR Authorization', 'db2', 'This will create a new schema', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (105, 35, 'Update', '--+Clone+the+Existing+Employees+Table+into+the+New+Schema%0ACREATE+TABLE+HR.EMPLOYEES+AS+%28SELECT+*+FROM+db2inst1.EMP%29+WITH+DATA%3B%0A%0A--+Alter+the+Cloned+Table%3A+Add+a+New+Column%0AALTER+TABLE+HR.EMPLOYEES+ADD+COLUMN+DEPARTMENT+VARCHAR%2850%29+DEFAULT+%27General%27%3B%0A%0A', 'Create an HR.Employees table', 'db2', 'This will create a HR,Employees table from an existing table db2inst1.EMP', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (106, 35, 'Select', 'SELECT+*+FROM+HR.EMPLOYEES+WHERE+EMPNO+%3D+%27000010%27%3B', 'Select from HR.Employees', 'db2', 'This will select a row from HR.Employees', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (107, 35, 'Update', '--+Update+a+Record+in+the+Cloned+Table%0AUPDATE+HR.EMPLOYEES+SET+SALARY+%3D+190000++WHERE+EMPNO+%3D+%27000010%27%3B', 'Update HR.Employees', 'db2', 'This will update a row in HR.Employees', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (108, 35, 'Delete', '--+Delete+a+Record+from+the+Cloned+Table%0ADELETE+FROM+HR.EMPLOYEES+WHERE+EMPNO+%3D+%27000010%27%3B', 'Delete HR.Employees', 'db2', 'This will delete a row in HR.Employees', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (100, 35, 'Policy Violation', 'REVOKE+DBADM+ON+DATABASE+FROM+USER+liher%3B%0AREVOKE+DBADM+ON+DATABASE+FROM+USER+jason%3B%0AREVOKE+DBADM+ON+DATABASE+FROM+USER+john%3B%0AREVOKE+DBADM+ON+DATABASE+FROM+USER+ian%3B', 'Revoke Permissions', 'db2', 'Revoke and Grant users access on DB2', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (111, 35, 'Update', '--+Grant+Database-Level+Privileges%0AGRANT+DBADM+ON+DATABASE+TO+USER+polly%3B%0AGRANT+DBADM+ON+DATABASE+TO+USER+liher%3B%0AGRANT+DBADM+ON+DATABASE+TO+USER+jason%3B%0AGRANT+DBADM+ON+DATABASE+TO+USER+john%3B%0AGRANT+DBADM+ON+DATABASE+TO+USER+ian%3B', 'Grant Permissions', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (112, 35, 'Update', '--+Grant+Role-Based+Superuser+Access+%28Optional%2C+for+Full+Admin+Rights%29%0AGRANT+SECADM%2C+DBADM%2C+DATAACCESS%2C+ACCESSCTRL+ON+DATABASE+TO+USER+polly%3B%0AGRANT+SECADM%2C+DBADM%2C+DATAACCESS%2C+ACCESSCTRL+ON+DATABASE+TO+USER+liher%3B%0AGRANT+SECADM%2C+DBADM%2C+DATAACCESS%2C+ACCESSCTRL+ON+DATABASE+TO+USER+jason%3B%0AGRANT+SECADM%2C+DBADM%2C+DATAACCESS%2C+ACCESSCTRL+ON+DATABASE+TO+USER+john%3B%0AGRANT+SECADM%2C+DBADM%2C+DATAACCESS%2C+ACCESSCTRL+ON+DATABASE+TO+USER+ian%3B%0A', 'Grant SuperUser Permissions', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (113, 35, 'Update', 'CREATE+TABLE+CUSTOMER_CREDITCARDS+%28CUSTOMER_ID+INTEGER+NOT+NULL+%2CNAME+VARCHAR%28100%29+NOT+NULL%2C+EMAIL+VARCHAR%28100%29+UNIQUE+NOT+NULL%2C+PHONE+VARCHAR%2820%29%2C+CREDIT_CARD_NUMBER+CHAR%2816%29+NOT+NULL%2C+EXPIRY_DATE+DATE+NOT+NULL%29%3B', 'Create customer_creditcards table', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (114, 35, 'Update', 'ALTER+TABLE+CUSTOMER_CREDITCARDS+ADD+COLUMN+CVV+SMALLINT+CHECK+%28CVV+BETWEEN+100+AND+999%29%3B', 'Alter customer_creditcards table', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (115, 35, 'Insert', 'INSERT+INTO+CUSTOMER_CREDITCARDS+%28CUSTOMER_ID%2C+NAME%2C+EMAIL%2C+PHONE%2C+CREDIT_CARD_NUMBER%2C+EXPIRY_DATE%2C+CVV%29+VALUES+%281%2C+%27Alice+Johnson%27%2C+%27alice%40gdemo.com%27%2C+%27555-1234%27%2C+%274111111111111111%27%2C+%272026-06-30%27%2C+123%29%2C+%282%2C+%27Bob+Smith%27%2C+%27bob%40gdemo.com%27%2C+%27555-5678%27%2C+%275500000000000004%27%2C+%272027-09-15%27%2C+456%29%2C+%283%2C+%27Charlie+Brown%27%2C+%27charlie%40gdemo.com%27%2C+%27555-9876%27%2C+%27340000000000009%27%2C+%272028-12-10%27%2C+789%29%3B', 'Insert into customer_creditcards table', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (116, 35, 'Select', 'SELECT+*+FROM+CUSTOMER_CREDITCARDS%3B', 'Select from customer_creditcards table', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (117, 35, 'Delete', 'DELETE+FROM+CUSTOMER_CREDITCARDS+WHERE+CUSTOMER_ID+%3D+2%3B', 'Delete from customer_creditcards table', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (118, 35, 'Drop', 'DROP+TABLE+CUSTOMER_CREDITCARDS%3B', 'Drop customer_creditcards table', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (120, 35, 'Outlier', 'select+*+from+DB2INST1.EMP+WHERE+1%3D1%3B', 'basic SQL injection', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (121, 35, 'Exceptions', 'SELECT+*+FROM+HR.SALARIES+WHERE+security_label+%3D+%27TOP_SECRET%27%3B', 'Bad where clause', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (122, 35, 'Exceptions', 'DROP+TABLE+CUSTOMERS%3B', 'Bad drop clause', 'db2', '', '', 1);
INSERT INTO public.tb_query (id, fk_tb_databaseconnections_id, query_db_type, query_string, query_usecase, query_type, query_description, video_link, query_loop) VALUES (119, 35, 'Exceptions', 'UPDATE+employees+SET+salary+%3D+salary+%2B+100+WHERE+emp_id+%3D+1%3B', 'Update non existent table', 'db2', '', '', 1);

INSERT INTO public.tb_stories (id, runtime, story) VALUES (4, NULL, '{"name": "DB2 Monitoring Sys Privilege Management", "story": [{"query_id": 100, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}, {"query_id": 111, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}, {"query_id": 112, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}], "video": "https://ibm.github.io/CyberSkill/?video=revokeAndGrantPermissions.mp4", "author": "polly", "handbook": "/handbooks/monitoringSysAdmin.pdf", "outcomes": "Understand how Guardium monitors privilege management", "description": "This simple story involves revoking and adding privilege. This story runs in the following flow. 1. Polly revokes user permissions. Sometime later (4 seconds)2. Polly grants permissions. Sometime later (4 seconds) 3. Polly grants greater permissions"}');
INSERT INTO public.tb_stories (id, runtime, story) VALUES (5, NULL, '{"name": "DB2 Monitoring table management", "story": [{"query_id": 113, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}, {"query_id": 114, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}, {"query_id": 115, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}, {"query_id": 116, "datasource": "db2_localhost_SAMPLE_jason", "pause_in_seconds": 4000}, {"query_id": 117, "datasource": "db2_localhost_SAMPLE_liher", "pause_in_seconds": 4000}, {"query_id": 118, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}], "video": "https://ibm.github.io/CyberSkill/?video=monitoringTableManagement.mp4", "author": "polly", "handbook": "/handbooks/monitoringTableManagement.pdf", "outcomes": "Understand how Guardium monitors table management", "description": "This simple story involves monitoring table managment. This story runs in the following flow. 1. Polly creates a table. Sometime later (4 seconds)2. Polly updates the table schema. Sometime later (4 seconds) 3. Polly inserts rows. Sometime later (4 seconds)1. Jason selects from the table. Sometime later (4 seconds)2. Liher deletes data from the table. Sometime later (4 seconds) 3. Polly drops the table"}');
INSERT INTO public.tb_stories (id, runtime, story) VALUES (6, NULL, '{"name": "DB2 Monitoring bad behaviour", "story": [{"query_id": 119, "datasource": "db2_localhost_SAMPLE_liher", "pause_in_seconds": 2000}, {"query_id": 120, "datasource": "db2_localhost_SAMPLE_liher", "pause_in_seconds": 2000}, {"query_id": 121, "datasource": "db2_localhost_SAMPLE_liher", "pause_in_seconds": 2000}, {"query_id": 122, "datasource": "db2_localhost_SAMPLE_liher", "pause_in_seconds": 2000}], "video": "https://ibm.github.io/CyberSkill/?video=monitoringBadBehaviour.mp4", "author": "liher", "handbook": "/handbooks/monitoringBadBehaviour.pdf", "outcomes": "Understand how Guardium monitors table management", "description": "This simple story involves monitoring bad behaviour. This is a short collection of activites that get detected in Guardium."}');
INSERT INTO public.tb_stories (id, runtime, story) VALUES (7, NULL, '{"name": "DB2 Monitoring Sys Admins", "story": [{"query_id": 104, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}, {"query_id": 105, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}, {"query_id": 106, "datasource": "db2_localhost_SAMPLE_jason", "pause_in_seconds": 4000}, {"query_id": 107, "datasource": "db2_localhost_SAMPLE_liher", "pause_in_seconds": 4000}, {"query_id": 106, "datasource": "db2_localhost_SAMPLE_jason", "pause_in_seconds": 4000}, {"query_id": 108, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}, {"query_id": 109, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}, {"query_id": 110, "datasource": "db2_localhost_SAMPLE_polly", "pause_in_seconds": 4000}], "video": "https://ibm.github.io/CyberSkill/?video=monitoringSysAdmin.mp4", "author": "polly", "handbook": "/handbooks/monitoringSysAdmin.pdf", "outcomes": "Understand how Guardium monitors system administrators", "description": "This simple story involves the creation and manipulation of a table and its users. Activities such as this show up in the DAM reports of Guardium. This story runs in the following flow. Polly our systems admin creates a schema. Polly then creates a table.  Jason, then selects from that table. Liher, then updates the table. Jason then reselects the same data from the table and sees a new value.  Polly then deletes the user from the table.  Polly then drops the table. Polly then drops the schema."}');

INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (13, 'db2_localhost_SAMPLE_liher', 'active', 'db2', '', 'liher', 'liher', '50000', 'SAMPLE', 'localhost', 'com.ibm.db2.jcc.DB2Driver', '', '', 'DBADM', 'Full Access');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (14, 'db2_localhost_SAMPLE_polly', 'active', 'db2', '', 'polly', 'polly', '50000', 'SAMPLE', 'localhost', 'com.ibm.db2.jcc.DB2Driver', '', '', 'DBADM', 'Full Access');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (15, 'db2_localhost_SAMPLE_john', 'active', 'db2', '', 'john', 'john', '50000', 'SAMPLE', 'localhost', 'com.ibm.db2.jcc.DB2Driver', '', '', 'Standard User', 'Select,Update,Insert,Delete');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (16, 'db2_localhost_SAMPLE_jason', 'active', 'db2', '', 'jason', 'jason', '50000', 'SAMPLE', 'localhost', 'com.ibm.db2.jcc.DB2Driver', '', '', 'Standard User', 'Select,Update,Insert,Delete');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (17, 'db2_localhost_SAMPLE_db2inst1', 'active', 'db2', '', 'db2inst1', 'db2inst1', '50000', 'SAMPLE', 'localhost', 'com.ibm.db2.jcc.DB2Driver', '', '', 'DBADM', 'Full Access');

UPDATE public.tb_version SET version = 'v01.0005';

