
version: '3.7'
services:
    postgres:
        image: postgres:11.13
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          # copy the sql script to create tables
          - ./dbSQL/createTables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # script to populate Levels
          - ./dbSQL/LevelInserts.sql:/docker-entrypoint-initdb.d/LevelInserts.sql
