-- GDP Lab Database Connection Inserts with Correct IP Addresses
-- PostgreSQL connections: 192.168.100.12
-- MySQL connections: 192.168.100.13
-- DB2 connections: 192.168.100.15

-- PostgreSQL Connections
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (1, 'postgresql_192.168.100.12_crm_john', 'active', 'postgresql', '14', 'john', 'Password1!', '5432', 'crm', '192.168.100.12', 'org.postgresql.Driver', '', '', 'Standard User', 'Select,Update,Insert,Delete,Usage');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (2, 'postgresql_192.168.100.12_crm_jason', 'active', 'postgresql', '14', 'jason', 'Password1!', '5432', 'crm', '192.168.100.12', 'org.postgresql.Driver', '', '', 'Standard User', 'Select,Update,Insert,Delete,Usage');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (3, 'postgresql_192.168.100.12_crm_liher', 'active', 'postgresql', '14', 'liher', 'Password1!', '5432', 'crm', '192.168.100.12', 'org.postgresql.Driver', '', '', 'Badguy', 'Superuser');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (4, 'postgresql_192.168.100.12_crm_polly', 'active', 'postgresql', '14', 'polly', 'Password1!', '5432', 'crm', '192.168.100.12', 'org.postgresql.Driver', '', '', 'DB Admin', 'Superuser');

-- MySQL Connections
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (5, 'mysql_192.168.100.13_crm_john', 'active', 'mysql', '10', 'john', 'Password1!', '3306', 'crm', '192.168.100.13', 'com.mysql.cj.jdbc.Driver', '', '', 'Standard User', 'Select,Update,Insert,Delete,Execute');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (6, 'mysql_192.168.100.13_crm_jason', 'active', 'mysql', '10', 'jason', 'Password1!', '3306', 'crm', '192.168.100.13', 'com.mysql.cj.jdbc.Driver', '', '', 'Standard User', 'Select,Update,Insert,Delete,Execute');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (7, 'mysql_192.168.100.13_crm_polly', 'active', 'mysql', '10', 'polly', 'Password1!', '3306', 'crm', '192.168.100.13', 'com.mysql.cj.jdbc.Driver', '', '', 'DB Admin', 'All Privileges');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (8, 'mysql_192.168.100.13_crm_liher', 'active', 'mysql', '10', 'liher', 'Password1!', '3306', 'crm', '192.168.100.13', 'com.mysql.cj.jdbc.Driver', '', '', 'Badguy', 'All Privileges');

-- DB2 Connections - CRM Database
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (9, 'db2_192.168.100.15_crm_polly', 'active', 'db2', '', 'polly', 'password', '50000', 'crm', '192.168.100.15', 'com.ibm.db2.jcc.DB2Driver', '', '', 'DBADM', 'Full Access');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (10, 'db2_192.168.100.15_crm_liher', 'active', 'db2', '', 'liher', 'password', '50000', 'crm', '192.168.100.15', 'com.ibm.db2.jcc.DB2Driver', '', '', 'DBADM', 'Full Access');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (11, 'db2_192.168.100.15_crm_jason', 'active', 'db2', '', 'jason', 'password', '50000', 'crm', '192.168.100.15', 'com.ibm.db2.jcc.DB2Driver', '', '', 'Standard User', 'Select,Update,Insert,Delete');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (12, 'db2_192.168.100.15_crm_john', 'active', 'db2', '', 'john', 'password', '50000', 'crm', '192.168.100.15', 'com.ibm.db2.jcc.DB2Driver', '', '', 'Standard User', 'Select,Update,Insert,Delete');

-- DB2 Connections - SAMPLE Database (1.0005 changes)
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (13, 'db2_192.168.100.15_SAMPLE_liher', 'active', 'db2', '', 'liher', 'liher', '50000', 'SAMPLE', '192.168.100.15', 'com.ibm.db2.jcc.DB2Driver', '', '', 'DBADM', 'Full Access');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (14, 'db2_192.168.100.15_SAMPLE_polly', 'active', 'db2', '', 'polly', 'polly', '50000', 'SAMPLE', '192.168.100.15', 'com.ibm.db2.jcc.DB2Driver', '', '', 'DBADM', 'Full Access');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (15, 'db2_192.168.100.15_SAMPLE_john', 'active', 'db2', '', 'john', 'john', '50000', 'SAMPLE', '192.168.100.15', 'com.ibm.db2.jcc.DB2Driver', '', '', 'Standard User', 'Select,Update,Insert,Delete');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (16, 'db2_192.168.100.15_SAMPLE_jason', 'active', 'db2', '', 'jason', 'jason', '50000', 'SAMPLE', '192.168.100.15', 'com.ibm.db2.jcc.DB2Driver', '', '', 'Standard User', 'Select,Update,Insert,Delete');
INSERT INTO public.tb_databaseconnections (id, db_connection_id, status, db_type, db_version, db_username, db_password, db_port, db_database, db_url, db_jdbcclassname, db_usericon, db_databaseicon, db_alias, db_access) VALUES (17, 'db2_192.168.100.15_SAMPLE_db2inst1', 'active', 'db2', '', 'db2inst1', 'db2inst1', '50000', 'SAMPLE', '192.168.100.15', 'com.ibm.db2.jcc.DB2Driver', '', '', 'DBADM', 'Full Access');

-- Made with Bob
